### ISSUE TITLE
idrissha's fork - modifications, new features and changes in upstream cefclient

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#216]
New features and modifications in indrissha fork at bitbucket, that are worth mentioning and may be merged with the upcoming Chrome 47 release. There is an ongoing big refactoring in Issue #208, so patches would need to be applied manually. Also outlined several changes in upstream cefclient application that may need to be ported as well (see at the bottom).
### New features:
- [ ] Custom scheme handlers (Issue #50). See [[1]](https://bitbucket.org/idrissha/cefpython/commits/d90da2fb43e809c4d2f1065018ef60b3cf2b579f).
- [ ] Custom context menu. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/adf861240e7b4b22660b9517bded3d1b21bbbbac)
- [ ] download handler, read comments for BC issues. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/274d2369b0387ef8e7b7cd421ebda037e93c30e6)
- [ ] display handler: OnFullScreenModeChange (Issue #120), OnFaviconURLChange, OnAudioStatusChange, OnVideoRectUpdate. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/1adc453303ba702107623e0129e9f072ed823713), [[2]](https://bitbucket.org/idrissha/cefpython/commits/292372c1108b99b2a1ee9dfa6637fb4fd949e9af), [[3]](https://bitbucket.org/idrissha/cefpython/commits/b2ab49e82ffbc59352b47fa19fc1715385cb6d8a), [[4]](https://bitbucket.org/idrissha/cefpython/commits/c8822f8f16555bd25294e63403aaa31f446afce5)
- [x] request handler: OnBeforeResourceLoad and OnResourceRedirect. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/c93a71b499eb59d593c35bda056848a920613854)
- [ ] print handler. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/4ebc5e83951f63f398857c22d60d4dde40fc4cda)
### Modifications:
- [x] browser NotifyMoveOrResizeStarted() - may require changes to examples. On Windows modify WindowUtils::OnSize() and similar. Should be called from WM_SIZE and WM_SIZING as in cefclient, caling it from  WM_SIZING is not required but shouln't hurt. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/cc443ad794aeaf06a1767110f0ace7a067333abc)
- [x] missing IMPLEMENT_REFCOUNTING in [request_context_context_handler.h](https://bitbucket.org/idrissha/cefpython/src/fd7f93257ce801b5eebf9c35819149deaec98517/cefpython/cef3/client_handler/request_context_handler.h?fileviewer=file-view-default#request_context_handler.h-41)
- [x] pygtk_.py 
  - [SetAsChild() and window.xid](https://bitbucket.org/idrissha/cefpython/src/fd7f93257ce801b5eebf9c35819149deaec98517/cefpython/cef3/linux/binaries_64bit/pygtk_.py?at=master&fileviewer=file-view-default#pygtk_.py-115)
  - [vbox.show() before creating browser?](https://bitbucket.org/idrissha/cefpython/src/fd7f93257ce801b5eebf9c35819149deaec98517/cefpython/cef3/linux/binaries_64bit/pygtk_.py?at=master&fileviewer=file-view-default#pygtk_.py-116)
  - [sys.argv passed to Initialize()](https://bitbucket.org/idrissha/cefpython/src/master/cefpython/cef3/linux/binaries_64bit/pygtk_.py?fileviewer=file-view-default#pygtk_.py-204)
- [ ]  Try MessageLoop() instead of MessageLoopWork() in GTK - seems to work fine. Test how it behaves in other examples as well (wx, qt). See [idrissha pygtk_.py](https://bitbucket.org/idrissha/cefpython/src/master/cefpython/cef3/linux/binaries_64bit/pygtk_.py?fileviewer=file-view-default) - MessageLoop() and removal of gtk.main_quit()
- [ ] Add "-g" flags also in cython setup.py files (it's already in makefiles) - it shouldn't [affect performance](http://stackoverflow.com/questions/10988318/g-is-using-the-g-flag-for-production-builds-a-good-idea), see [[1]](https://bitbucket.org/idrissha/cefpython/src/master/cefpython/cef3/linux/setup/setup.py?fileviewer=file-view-default#setup.py-98)
- [x] [Focus issues fixed](https://bitbucket.org/idrissha/cefpython/commits/61c1533c6601a33e5831b2272ea9d4d58107cfe0?at=master#chg-cefpython/cef3/linux/binaries_64bit/pygtk_.py) in latest CEF, modify pygtk_.py by adding "focus-in-event" and check other examples as well
- [ ] python-debug instead of python-dbg on Fedora, see [[1]](https://bitbucket.org/idrissha/cefpython/commits/fd7f93257ce801b5eebf9c35819149deaec98517#chg-cefpython/cef3/linux/compile.py)
- [x] gtk-x11-2.0 lib, see [[1]](https://bitbucket.org/idrissha/cefpython/commits/fd7f93257ce801b5eebf9c35819149deaec98517#chg-cefpython/cef3/linux/setup/setup.py)
- [ ] commandLineArgs and conversion of sys.argv in Initialize() - commandLineArgs should be added as 3rd parameter for BC, see [[1]](https://bitbucket.org/idrissha/cefpython/commits/fd7f93257ce801b5eebf9c35819149deaec98517#chg-cefpython/cefpython.pyx) and [[2]](https://bitbucket.org/idrissha/cefpython/src/master/cefpython/cefpython.pyx?fileviewer=file-view-default#cefpython.pyx-346)
- [ ] linux.pxd - gtkplug.h required with newer Cython? See [[1]](https://bitbucket.org/idrissha/cefpython/src/master/cefpython/cython_includes/linux.pxd?fileviewer=file-view-default#linux.pxd-9)
- [ ] add an example of quitting message loop by using OnAfterCreated and OnBeforeClose and browser counting, see [[1]](https://bitbucket.org/idrissha/cefpython/src/48c04312b5d5/cefpython/lifespan_handler_cef3.pyx?at=master&fileviewer=file-view-default#lifespan_handler_cef3.pyx-106)
- [x] window_info_cef3.pyx - rect param on Linux, see [[1]](https://bitbucket.org/idrissha/cefpython/src/48c04312b5d5/cefpython/window_info_cef3.pyx?at=master&fileviewer=file-view-default#window_info_cef3.pyx-36)
- [x] cef_version.h - to discuss, read comments. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/2a6fb9adee27b3ca48f9515e97f4100c737eab21#comment-2800385)
- [x] ShowDevTools in context menu, see [[1]](https://bitbucket.org/idrissha/cefpython/commits/8f77d54d47c83e74f9e220ad502fce35c859c067)
- [x] cookie funcs signatures changed, see [[1]](https://bitbucket.org/idrissha/cefpython/commits/ed4ef2e1ab1b21b3d35cfa9134fa812db5643eda#Lcefpython/cookie_cef3.pyxF180T180), [[2]](https://bitbucket.org/idrissha/cefpython/commits/ed4ef2e1ab1b21b3d35cfa9134fa812db5643eda#Lcefpython/cython_includes/cef_cookie_cef3.pxdF8T8), [[3]](https://bitbucket.org/idrissha/cefpython/commits/ed4ef2e1ab1b21b3d35cfa9134fa812db5643eda#Lcefpython/cython_includes/cef_cookie_manager_namespace.pxdF2T2), [[4]](https://bitbucket.org/idrissha/cefpython/commits/ed4ef2e1ab1b21b3d35cfa9134fa812db5643eda#Lcefpython/cython_includes/cef_runnable.pxdF10T10)
- [x] callbacks, context, runnable - see [[1]](https://bitbucket.org/idrissha/cefpython/commits/ed4ef2e1ab1b21b3d35cfa9134fa812db5643eda#chg-cefpython/cython_includes/cef_callback_cef3.pxd)
- [x] OnBeforePopup new parameters, see [[1]](https://bitbucket.org/idrissha/cefpython/commits/dbf75b0b7c89decac4d3e6653adb681ec466ed84)
- [ ] -std=gnu++11 flag in Makefiles. See [[1]](https://bitbucket.org/idrissha/cefpython/commits/4c9e306df4c99b44871eff0f04407f22e486a501#Lcefpython/cef3/subprocess/MakefileF29)
### Upstream cefclient code changes:
- [x] xlib error handler. See [[1]](https://bitbucket.org/chromiumembedded/cef/src/b660893c6e800374d2b908a0b56ca47441ea2135/tests/cefclient/cefclient_gtk.cc?at=2526&fileviewer=file-view-default#cefclient_gtk.cc-31)
- [ ] a copy of argv for CefMainArgs. See [[1]](https://bitbucket.org/chromiumembedded/cef/src/b660893c6e800374d2b908a0b56ca47441ea2135/tests/cefclient/cefclient_gtk.cc?at=2526&fileviewer=file-view-default#cefclient_gtk.cc-52)
- [ ] CefEnableHighDPISupport(). See [[1]](https://bitbucket.org/chromiumembedded/cef/src/b660893c6e800374d2b908a0b56ca47441ea2135/tests/cefclient/cefclient_win.cc?at=2526&fileviewer=file-view-default#cefclient_win.cc-36)
- [ ] maybe expose a function get process type. See [[1]](https://bitbucket.org/chromiumembedded/cef/src/b660893c6e800374d2b908a0b56ca47441ea2135/tests/cefclient/cefclient_win.cc?at=2526&fileviewer=file-view-default#cefclient_win.cc-55)
- [ ] When window is minimized set browser size to 0x0 to reduce resource usage. Update examples? Maybe a default implementation on Win in WindowUtils::OnMinimze()? See [[1]](https://github.com/cztomczak/phpdesktop/issues/179)
